# Generated by Django 4.2.2 on 2023-06-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoadmin',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactoadmin',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='contactoadmin',
            name='rut',
            field=models.CharField(max_length=11),
        ),
    ]
