# Generated by Django 4.2.2 on 2023-06-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_contactoadmin_email_alter_contactoadmin_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoadmin',
            name='genero',
            field=models.IntegerField(choices=[(0, 'helicoptero apache'), (1, 'Femenino'), (2, 'Masculino')], default=1),
        ),
    ]
