# Generated by Django 4.2.2 on 2023-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_contactoadmin_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=30)),
                ('categoriaP', models.CharField(max_length=30)),
                ('modelovehiculoP', models.CharField(max_length=30)),
                ('precioP', models.IntegerField()),
            ],
        ),
    ]
